# Generated by Django 4.0.2 on 2022-02-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_specialized_in_teacher_user_student_user'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='accounts.Student', verbose_name='Enrolled students'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='accounts.Teacher', verbose_name='Course teachers'),
        ),
        migrations.AlterField(
            model_name='video',
            name='watched_by',
            field=models.ManyToManyField(to='accounts.Student', verbose_name='Watched by'),
        ),
    ]
