# Generated by Django 4.0.2 on 2022-03-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_comment_blog_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Course Image Link'),
        ),
    ]
