# Generated by Django 4.0.2 on 2022-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Course Image Link'),
        ),
    ]
