# Generated by Django 4.0.2 on 2022-03-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Banner image link'),
        ),
    ]
