# Generated by Django 4.0.2 on 2022-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_comment_blog_alter_comment_user_and_more'),
        ('accounts', '0003_teacher_specialized_in_teacher_user_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specialized_in',
            field=models.ManyToManyField(blank=True, to='course.CourseCategory', verbose_name='Expertise in'),
        ),
    ]
